spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: estoque

server:
      port: 8081

application:

    name: cliente # Nome do seu aplicativo

    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka
